### ISSUE TITLE
Array OOB when Essentials compat is enabled

### ISSUE THREAD

**Issue by kadenscott** [kadenscott/RandomSpawnPlus#6]
```
[04:39:05 WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[04:39:05 WARN]:        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
[04:39:05 WARN]:        at java.util.ArrayList.get(ArrayList.java:433)
[04:39:05 WARN]:        at com.apt.randomspawnplus.util.SpawnProvider.getSpawn(SpawnProvider.java:43)
[04:39:05 WARN]:        at com.apt.randomspawnplus.listeners.RSPDeathListener.onDeath(RSPDeathListener.java:23)
[04:39:05 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor48.execute(Unknown Source)
[04:39:05 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[04:39:05 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[04:39:05 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[04:39:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:674)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:599)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2089)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInClientCommand.a(SourceFile:30)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInClientCommand.a(SourceFile:8)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172)
[04:39:05 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[04:39:05 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by kadenscott** [comment]
This error was hidden because I wasn't printing the stacktrace. Silly me.
